# Generated by Django 4.2.4 on 2023-09-14 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import lanche.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preco')),
                ('categoria', models.CharField(default='cat', max_length=20, verbose_name='Categoria')),
                ('ingredientes', models.TextField(max_length=300, verbose_name='Ingredientes')),
                ('date_lanche', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_lanche', models.ImageField(blank=True, upload_to=lanche.models.get_file_path)),
                ('publicado', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario')),
            ],
        ),
    ]
