# Generated by Django 4.2.4 on 2023-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('rg', models.CharField(max_length=11, verbose_name='rg')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereco')),
            ],
        ),
    ]
