INSERT INTO lanche_lanche(
    nome, preco, categoria, ingredientes, publicado, date_lanche, funcionario_id)
    ('X-BAURU', 28, 'Bauru', 'Pão, rosbife, queijo, tomate, alface', 1, '2023-09-21', 1),
    ('X-FRANGO', 25, 'Frango', 'Pão, peito de frango grelhado, queijo, alface, tomate', 1, '2023-09-21', 1),
    ('X-VEGETARIANO', 22, 'Vegetariano', 'Pão integral, almôndegas de soja, queijo vegano, alface, tomate', 1, '2023-09-21', 1),
    ('X-CALABRESA', 30, 'Calabresa', 'Pão, linguiça calabresa, queijo, cebola, pimentão', 1, '2023-09-21', 1),
    ('X-FRANGO CATUPIRY', 32, 'Frango com Catupiry', 'Pão, frango desfiado, catupiry, alface, tomate', 1, '2023-09-21', 1),
    ('X-BACON', 26, 'Bacon', 'Pão, bacon, carne bovina, queijo, alface, tomate', 1, '2023-09-21', 1),
    ('X-PRESUNTO', 27, 'Presunto', 'Pão, presunto, queijo, alface, tomate', 1, '2023-09-21', 1),
    ('X-ATUM', 24, 'Atum', 'Pão, atum, maionese, alface, tomate', 1, '2023-09-21', 1),
    ('X-FRANGO CROCANTE', 33, 'Frango Crocante', 'Pão, peito de frango empanado, queijo, alface, molho especial', 1, '2023-09-21', 1),
    ('X-EGG', 29, 'Egg Burger', 'Pão, hambúrguer, ovo frito, queijo, alface, tomate', 1, '2023-09-21', 1),
    ('X-VEGGIE', 25, 'Veggie Burger', 'Pão integral, hambúrguer de feijão preto, abacate, alface, cebola roxa', 1, '2023-09-21', 1),
    ('X-TOFU', 27, 'Tofu Burger', 'Pão, hambúrguer de tofu grelhado, abacate, alface, tomate', 1, '2023-09-21', 1),
    ('X-PICANTE', 29, 'Burger Picante', 'Pão, hambúrguer, pimenta jalapeño, queijo, alface, molho picante', 1, '2023-09-21', 1),
    ('X-CHICKEN', 28, 'Chicken Burger', 'Pão, hambúrguer de frango, queijo, alface, cebola caramelizada', 1, '2023-09-21', 1),
    ('X-VEGAN', 26, 'Vegan Burger', 'Pão vegano, hambúrguer de grão-de-bico, alface, cebola roxa, molho tahini', 1, '2023-09-21', 1),
    ('X-SALMÃO', 32, 'Salmão Burger', 'Pão de centeio, hambúrguer de salmão, cream cheese, alface, cebola roxa', 1, '2023-09-21', 1),
    ('X-ALHO PORÓ', 30, 'Burger de Alho-Poró', 'Pão, hambúrguer de alho-poró, queijo, alface, maionese de alho', 1, '2023-09-21', 1),
    ('X-PICANHA', 35, 'Picanha Burger', 'Pão, hambúrguer de picanha, queijo, alface, cebola crispy', 1, '2023-09-21', 1),
    ('X-VEGGIE SUPREMO', 32, 'Veggie Supremo', 'Pão integral, hambúrguer de grão-de-bico, abacate, alface, tomate, maionese vegana', 1, '2023-09-21', 1),
    ('X-MAÇÃ', 27, 'Burger de Maçã', 'Pão, hambúrguer de carne, maçã verde, alface, molho de mostarda', 1, '2023-09-21', 1),
    ('X-QUEIJO', 24, 'Burger de Queijo', 'Pão, hambúrguer, queijo cheddar, alface, cebola caramelizada', 1, '2023-09-21', 1),
    ('X-COSTELA', 36, 'Costela Burger', 'Pão, hambúrguer de costela, queijo provolone, alface, cebola roxa, molho barbecue', 1, '2023-09-21', 1),
    ('X-SALADA', 26, 'Salad Burger', 'Pão integral, hambúrguer de peru, alface, tomate, cenoura ralada, molho de iogurte', 1, '2023-09-21', 1),
    ('X-SURPRESA', 40, 'Burger Surpresa', 'Pão, hambúrguer surpresa do chef, ingredientes especiais', 1, '2023-09-21', 1),
    ('X-TEMPERO', 31, 'Burger com Tempero', 'Pão, hambúrguer, queijo suíço, alface, tomate, molho especial', 1, '2023-09-21', 1).\